// Package docker generates the Dockerfile, docker-compose.yml and .env that
// the Docker install path renders into ~/.solsclaw/docker. The compose file
// can include a Tailscale sidecar following the upstream guide:
//
//	https://tailscale.com/docs/features/containers/docker/how-to/connect-docker-container
//
// We deliberately keep the Dockerfile simple — node:22 base image, npm install
// of openclaw, run as root inside the container with state mounted from the
// host. Users who need rootless / hardened setups can edit the generated
// files; we never overwrite them on a re-run without a backup.
package docker

import (
	"bytes"
	"text/template"
)

// Plan is the rendered set of files that get written to disk.
type Plan struct {
	Dockerfile    string
	ComposeYAML   string
	EnvFile       string
	DataDirName   string // relative to the docker dir
	UseTailscale  bool
	HasOpenAIPort bool
}

// Inputs to drive template rendering. Everything secret (API key, Tailscale
// auth key) is funnelled into the .env file so the compose file itself can
// be checked into git or shared without leaking credentials.
type Inputs struct {
	Provider             string
	APIKey               string
	OpenAIGatewayEnabled bool
	TailscaleEnabled     bool
	TailscaleHostname    string
	TailscaleAuthKey     string
}

const dockerfileTpl = `# Generated by solsclaw — edit if you need a different base image.
FROM node:22-bookworm-slim

RUN apt-get update \
 && apt-get install -y --no-install-recommends ca-certificates curl \
 && rm -rf /var/lib/apt/lists/*

# OpenClaw is a Node CLI; install it globally so 'openclaw' is on PATH.
RUN npm install -g openclaw@latest

# Persistent state lives in /root/.openclaw, mounted as a volume from the host.
WORKDIR /root
EXPOSE 18789

ENTRYPOINT ["openclaw"]
CMD ["gateway", "start"]
`

const composeNoTSTpl = `# Generated by solsclaw. Re-run the installer to regenerate.
services:
  openclaw:
    build: .
    image: solsclaw/openclaw:local
    container_name: solsclaw-openclaw
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./{{.DataDirName}}:/root/.openclaw
{{if .HasOpenAIPort}}    ports:
      - "127.0.0.1:18789:18789"
{{end}}`

// Tailscale sidecar pattern: the Tailscale container owns the network
// namespace; the openclaw container joins it via network_mode: service:.
// This way OpenClaw is reachable on the tailnet at the configured hostname
// without exposing any host port. See:
// https://tailscale.com/docs/features/containers/docker/how-to/connect-docker-container
const composeWithTSTpl = `# Generated by solsclaw. Re-run the installer to regenerate.
services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: solsclaw-tailscale
    hostname: {{.TailscaleHostname}}
    restart: unless-stopped
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY?TS_AUTHKEY missing in .env}
      - TS_HOSTNAME={{.TailscaleHostname}}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
{{if .HasOpenAIPort}}      - TS_SERVE_CONFIG=/config/serve.json
{{end}}    volumes:
      - ./tailscale-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module

  openclaw:
    build: .
    image: solsclaw/openclaw:local
    container_name: solsclaw-openclaw
    restart: unless-stopped
    network_mode: service:tailscale
    depends_on:
      - tailscale
    env_file: .env
    volumes:
      - ./{{.DataDirName}}:/root/.openclaw
`

// Render produces the file set to write to disk.
func Render(in Inputs) (Plan, error) {
	plan := Plan{
		DataDirName:   "openclaw-data",
		UseTailscale:  in.TailscaleEnabled,
		HasOpenAIPort: in.OpenAIGatewayEnabled,
	}
	plan.Dockerfile = dockerfileTpl

	composeRaw := composeNoTSTpl
	if in.TailscaleEnabled {
		composeRaw = composeWithTSTpl
	}
	tpl, err := template.New("compose").Parse(composeRaw)
	if err != nil {
		return Plan{}, err
	}
	tplData := struct {
		Plan
		TailscaleHostname string
	}{
		Plan:              plan,
		TailscaleHostname: in.TailscaleHostname,
	}
	var buf bytes.Buffer
	if err := tpl.Execute(&buf, tplData); err != nil {
		return Plan{}, err
	}
	plan.ComposeYAML = buf.String()

	plan.EnvFile = renderEnv(in)
	return plan, nil
}

func renderEnv(in Inputs) string {
	var b bytes.Buffer
	b.WriteString("# Generated by solsclaw. Contains secrets — keep this file 0600 and out of git.\n")
	if in.APIKey != "" {
		// Provider-scoped name so multiple providers can co-exist if the
		// user later edits the compose file by hand.
		b.WriteString("SOLSCLAW_PROVIDER=" + in.Provider + "\n")
		b.WriteString("SOLSCLAW_API_KEY=" + in.APIKey + "\n")
	}
	if in.TailscaleEnabled {
		b.WriteString("TS_AUTHKEY=" + in.TailscaleAuthKey + "\n")
		b.WriteString("TS_HOSTNAME=" + in.TailscaleHostname + "\n")
	}
	return b.String()
}
