package steps

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"runtime"

	"github.com/SolsticeSauer/solsclaw_beta/internal/installer"
	"github.com/SolsticeSauer/solsclaw_beta/internal/platform"
)

const (
	envBlockBegin = "# >>> solsclaw env >>>"
	envBlockEnd   = "# <<< solsclaw env <<<"
)

// SetupShellPath makes the `openclaw` binary reachable from a fresh
// interactive shell. After install-openclaw succeeds, the executable
// lives at ~/.solsclaw/runtime/node/bin/openclaw — but that directory
// is only on the installer process' PATH, not on the user's login PATH.
//
// We render ~/.solsclaw/env.sh (the single source of truth) and append a
// guarded source-line to the user's shell rc files so future shells
// pick it up automatically. The block is idempotent via begin/end
// markers, so re-running the installer doesn't duplicate entries.
//
// In Docker mode the host has no `openclaw` binary at all; we instead
// drop a thin wrapper at ~/.solsclaw/bin/openclaw that forwards to
// `docker compose exec`, and put that on PATH the same way.
type SetupShellPath struct{}

func (SetupShellPath) ID() string    { return "setup-shell-path" }
func (SetupShellPath) Label() string { return "Add solsclaw paths to your shell" }

func (SetupShellPath) ShouldRun(_ installer.StepContext) bool {
	// Native Windows users don't get a POSIX shell rc; skipping
	// rather than guessing. WSL users hit the linux branch correctly.
	return runtime.GOOS != "windows"
}

func (s SetupShellPath) Run(_ context.Context, sc installer.StepContext) error {
	home := platform.InstallerHome()
	if err := os.MkdirAll(home, 0o755); err != nil {
		return err
	}

	var (
		pathDirs   []string
		noOpReason string
	)

	switch sc.Submission.InstallMode {
	case installer.ModeNative:
		nodeBin := filepath.Join(home, "runtime", "node", "bin")
		if _, err := os.Stat(nodeBin); err == nil {
			pathDirs = append(pathDirs, nodeBin)
		} else {
			// Pre-existing system Node was used; openclaw landed in the
			// system's npm prefix and is already on the user's PATH. We
			// still write env.sh as a clearly-marked no-op so users who
			// follow the documented `source ~/.solsclaw/env.sh` workflow
			// don't hit a "no such file" error.
			noOpReason = "system Node was already on PATH at install time, so nothing to add"
		}
	case installer.ModeDocker:
		wrapperDir := filepath.Join(home, "bin")
		if err := writeDockerWrapper(wrapperDir); err != nil {
			return fmt.Errorf("write docker wrapper: %w", err)
		}
		pathDirs = append(pathDirs, wrapperDir)
		sc.Bus.Log(s.ID(), "info", "Wrote `openclaw` docker wrapper at "+filepath.Join(wrapperDir, "openclaw"))
	}

	envPath := filepath.Join(home, "env.sh")
	if err := writeEnvFile(envPath, pathDirs, noOpReason); err != nil {
		return fmt.Errorf("write env.sh: %w", err)
	}
	sc.Bus.Log(s.ID(), "info", "Wrote "+envPath)

	// Only touch shell rc files when we actually have something to add to
	// PATH. A no-op env.sh would just be visual noise in someone's
	// .bashrc / .zshrc.
	if len(pathDirs) > 0 {
		updated, skipped := appendToShellRCs(envPath)
		for _, p := range updated {
			sc.Bus.Log(s.ID(), "info", "Updated "+p)
		}
		for _, p := range skipped {
			sc.Bus.Log(s.ID(), "info", "Already configured: "+p)
		}
		sc.Bus.Log(s.ID(), "info",
			"For the current shell: source "+envPath+
				" — new shells pick this up automatically.")
	} else {
		sc.Bus.Log(s.ID(), "info", noOpReason+"; openclaw should already be reachable in any shell.")
	}
	return nil
}

// writeEnvFile produces a tiny POSIX-shell snippet that prepends our paths
// to PATH only if they're not already there. Surviving multiple sources
// without ballooning PATH matters because some terminals re-read rc files
// on every new tab.
//
// When `dirs` is empty (e.g. the user already had system Node on PATH so
// the portable-Node bin directory was never created), we still write the
// file as a documented no-op. That way the documented `source ~/.solsclaw/
// env.sh` workflow always succeeds — it just does nothing in this case.
func writeEnvFile(path string, dirs []string, noOpReason string) error {
	var buf bytes.Buffer
	buf.WriteString("# Generated by solsclaw — re-run the installer to regenerate.\n")
	if len(dirs) == 0 {
		buf.WriteString("# " + noOpReason + ".\n")
		buf.WriteString("# This file is intentionally a no-op; sourcing it has no effect.\n")
		return os.WriteFile(path, buf.Bytes(), 0o644)
	}
	buf.WriteString("# Adds the directories below to PATH if they aren't already there.\n\n")
	for _, dir := range dirs {
		fmt.Fprintf(&buf,
			`case ":${PATH}:" in
  *":%s:"*) ;;
  *) export PATH="%s:$PATH" ;;
esac
`, dir, dir)
	}
	return os.WriteFile(path, buf.Bytes(), 0o644)
}

// writeDockerWrapper drops a small shim that lets users type
// `openclaw chat "hi"` on the host even though the binary lives inside
// the compose stack.
func writeDockerWrapper(binDir string) error {
	if err := os.MkdirAll(binDir, 0o755); err != nil {
		return err
	}
	composeFile := filepath.Join(platform.DockerDir(), "docker-compose.yml")
	wrapper := fmt.Sprintf(`#!/bin/sh
# Generated by solsclaw — proxies host calls to the openclaw container.
exec docker compose -f %q exec -T openclaw openclaw "$@"
`, composeFile)
	return os.WriteFile(filepath.Join(binDir, "openclaw"), []byte(wrapper), 0o755)
}

// appendToShellRCs walks the candidate rc files and appends a guarded
// block that sources env.sh. Returns the files actually updated and
// those that were already configured.
func appendToShellRCs(envPath string) (updated, skipped []string) {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return nil, nil
	}
	candidates := []string{
		filepath.Join(homeDir, ".bashrc"),
		filepath.Join(homeDir, ".bash_profile"),
		filepath.Join(homeDir, ".zshrc"),
		filepath.Join(homeDir, ".profile"),
	}
	block := fmt.Sprintf("\n%s\n[ -f %q ] && . %q\n%s\n",
		envBlockBegin, envPath, envPath, envBlockEnd)

	for _, rc := range candidates {
		data, err := os.ReadFile(rc)
		if err != nil {
			// We deliberately do NOT create rc files that don't exist —
			// users who never set up bash shouldn't suddenly have a .bashrc.
			continue
		}
		if bytes.Contains(data, []byte(envBlockBegin)) {
			skipped = append(skipped, rc)
			continue
		}
		f, err := os.OpenFile(rc, os.O_APPEND|os.O_WRONLY, 0)
		if err != nil {
			continue
		}
		_, werr := f.WriteString(block)
		_ = f.Close()
		if werr == nil {
			updated = append(updated, rc)
		}
	}
	return updated, skipped
}
